FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["src/API/Blog.API.csproj", "src/API/"]
COPY ["src/Application/Blog.Application.csproj", "src/Application/"]
COPY ["src/Domain/Blog.Domain.csproj", "src/Domain/"]
COPY ["src/Infrastructure/Blog.Infrastructure.csproj", "src/Infrastructure/"]
COPY ["Blog.sln", "./"]

RUN dotnet restore

COPY . .

RUN dotnet publish "src/API/Blog.API.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=build /app/publish .
EXPOSE 80
EXPOSE 443

ENV ASPNETCORE_URLS=http://+:80
ENV ASPNETCORE_ENVIRONMENT=Production

ENTRYPOINT ["dotnet", "Blog.API.dll"]